jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Set jadx version
      run: 'JADX_REV=$(git rev-list --count HEAD)

        JADX_VERSION="r${JADX_REV}.${GITHUB_SHA:0:7}"

        echo "JADX_VERSION=$JADX_VERSION" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: dist copyExe
    - continue-on-error: true
      name: Save bundle artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: ${{ format('jadx-{0}', env.JADX_VERSION) }}
        path: build/jadx/**/*
        retention-days: 14
    - continue-on-error: true
      name: Save exe artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: ${{ format('jadx-gui-{0}-no-jre-win.exe', env.JADX_VERSION) }}
        path: build/*.exe
        retention-days: 14
  build-win-bundle:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: oracle-actions/setup-java@v1
      with:
        release: 21
    - continue-on-error: true
      name: Print Java version
      run: java -version
      shell: bash
    - continue-on-error: true
      name: Set jadx version
      run: 'JADX_REV=$(git rev-list --count HEAD)

        JADX_VERSION="r${JADX_REV}.${GITHUB_SHA:0:7}"

        echo "JADX_VERSION=$JADX_VERSION" >> $GITHUB_ENV

        '
      shell: bash
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: dist -PbundleJRE=true
    - continue-on-error: true
      name: Save exe bundle artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: ${{ format('jadx-gui-{0}-with-jre-win', env.JADX_VERSION) }}
        path: jadx-gui/build/*-with-jre-win/*
        retention-days: 14
name: Build Artifacts
on:
  repository_dispatch:
    types: trigger-ga___build-artifacts.yml
